name: Elixir CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sync_service
    env:
      MIX_ENV: test
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DATABASE: electric
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 54321:5432
    steps:
      - uses: actions/checkout@v4
      - name: "Set PG settings"
        run: |
          docker exec ${{ job.services.postgres.id }} sh -c 'echo "wal_level=logical" >> /var/lib/postgresql/data/postgresql.conf'
          docker restart ${{ job.services.postgres.id }}
      - uses: erlef/setup-beam@v1
        with:
          version-type: strict
          version-file: '.tool-versions'
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: sync_service/deps
          key: ${{ runner.os }}-mix-${{ hashFiles('sync_service/**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Restore compiled code
        uses: actions/cache/restore@v4
        with:
          path: |
            sync_service/_build/*/lib
            !sync_service/_build/*/lib/electric
          key: ${{ runner.os }}-build-${{ hashFiles('sync_service/**/mix.lock') }}
      - name: Install dependencies
        run: mix deps.get && mix deps.compile
      - name: Save compiled code
        uses: actions/cache/save@v4
        with:
          path: |
            sync_service/_build/*/lib
            !sync_service/_build/*/lib/electric
          key: ${{ runner.os }}-build-${{ hashFiles('sync_service/**/mix.lock') }}
      - name: Compiles without warnings
        run: mix compile --force --all-warnings --warnings-as-errors
      # - run: mix start_dev
      - name: Run tests
        run: mix test
  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sync_service
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          version-type: strict
          version-file: '.tool-versions'
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: sync_service/deps
          key: ${{ runner.os }}-mixdeps-${{ hashFiles('sync_service/**/mix.lock') }}
      - run: mix deps.get
      - run: mix format --check-formatted
