name: Elixir CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sync_service
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          version-file: '.tool-versions'
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: sync_service/deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Restore compiled code
        uses: actions/cache/restore@v4
        with:
          path: |
            components/electric/_build/*/lib
            !components/electric/_build/*/lib/electric
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
      - name: Install dependencies
        run: mix deps.get && mix deps.compile
      - name: Save compiled code
        uses: actions/cache/save@v4
        with:
          path: |
            components/electric/_build/*/lib
            !components/electric/_build/*/lib/electric
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
      - name: Compiles without warnings
        run: mix compile --force --all-warnings --warnings-as-errors
      - name: Run tests
        run: mix test
  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: components/electric
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          version-file: '.tool-versions'
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: components/electric/deps
          key: ${{ runner.os }}-mixdeps-${{ hashFiles('components/electric/**/mix.lock') }}
      - run: mix deps.get
      - run: mix format --check-formatted
