name: TS tests

on:
  push:
    branches: ['main']
  pull_request:

permissions:
  contents: read

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/typescript_client
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          version-type: strict
          version-file: '.tool-versions'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: packages/typescript_client/package-lock.json
      - run: npm ci
      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: packages/sync_service/deps
          key: ${{ runner.os }}-mix-${{ hashFiles('sync_service/**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Restore compiled code
        uses: actions/cache@v4
        with:
          path: |
            packages/sync_service/_build/*/lib
            !packages/sync_service/_build/*/lib/electric
          key: ${{ runner.os }}-build-dev-${{ hashFiles('sync_service/**/mix.lock') }}
      - name: Install dependencies
        run: mix deps.get && mix deps.compile
        working-directory: packages/sync_service
      - name: Compiles without warnings
        run: mix compile --force --all-warnings --warnings-as-errors
        working-directory: packages/sync_service
      - uses: JarvusInnovations/background-action@v1
        name: Bootstrap System Under Test (SUT)
        with:
          run: |
            mix start_dev
            mix run --no-halt &

          wait-on: |
            http://localhost:3000

          tail: true
          log-output-resume: stderr
          wait-for: 1m
          log-output: true
          log-output-if: failure
          working-directory: packages/sync_service
      - name: Adjust Permissions
        run: |
          sudo chown -R runner:docker /home/runner/work/electric-next/electric-next/
          sudo chmod -R 775 /home/runner/work/electric-next/electric-next/
      - run: npm test
  style_check:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            packages/typescript_client/package-lock.json
            examples/**/package-lock.json
      - run: npm ci
        working-directory: packages/typescript_client
      - name: npm ci in each examples dir
        run: for dir in examples/*/; do (cd "$dir" && npm ci); done
      - run: npm run stylecheck
        working-directory: packages/typescript_client
  type_check:
    name: Type checking
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/typescript_client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: packages/typescript_client/package-lock.json
      - run: npm ci
      - run: npm run typecheck
  list_examples:
    name: List examples
    runs-on: ubuntu-latest
    outputs:
      example_names: ${{ steps.list_examples.outputs.example_names }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "example_names=`ls -d examples/*/ | jq -R -s -c 'split("\n")[:-1] | map(rtrimstr("/"))'`" >> $GITHUB_OUTPUT
        id: list_examples
  check_and_build_examples:
    name: Check and build ${{ matrix.example_folder }}
    needs: [list_examples, build_and_test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example_folder: ${{ fromJson(needs.list_examples.outputs.example_names) }}
    defaults:
      run:
        working-directory: ${{ matrix.example_folder }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            packages/typescript_client/package-lock.json
            ${{ matrix.example_folder }}/package-lock.json
      - name: npm ci in the repository root
        run: npm ci
        working-directory: packages/typescript_client
      - name: npm ci in the ${{ matrix.example_folder }}
        run: npm ci
      - run: npm run typecheck
      - run: npm run build
