name: TS tests

on:
  push:
    branches: ['main']
  pull_request:

permissions:
  contents: read

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/typescript-client
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          version-type: strict
          version-file: '.tool-versions'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: packages/sync-service/deps
          key: ${{ runner.os }}-mix-${{ hashFiles('sync-service/**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Restore compiled code
        uses: actions/cache@v4
        with:
          path: |
            packages/sync-service/_build/*/lib
            !packages/sync-service/_build/*/lib/electric
          key: ${{ runner.os }}-build-dev-${{ hashFiles('sync-service/**/mix.lock') }}
      - name: Install dependencies
        run: mix deps.get && mix deps.compile
        working-directory: packages/sync-service
      - name: Compiles without warnings
        run: mix compile --force --all-warnings --warnings-as-errors
        working-directory: packages/sync-service
      - uses: JarvusInnovations/background-action@v1
        name: Bootstrap System Under Test (SUT)
        with:
          run: |
            mix start_dev
            mix run --no-halt &

          wait-on: |
            http://localhost:3000

          tail: true
          log-output-resume: stderr
          wait-for: 1m
          log-output: true
          log-output-if: failure
          working-directory: packages/sync-service
      - name: Adjust Permissions
        run: |
          sudo chown -R runner:docker /home/runner/work/electric-next/electric-next/
          sudo chmod -R 775 /home/runner/work/electric-next/electric-next/
      - run: npm test
  style_check:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm stylecheck
        working-directory: packages/typescript-client
  type_check:
    name: Type checking
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/typescript-client
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm typecheck
  check_and_build_react_hooks:
    name: Check and build React hooks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/react-hooks
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
        name: pnpm build the typescript client
        working-directory: packages/typescript-client
      - run: pnpm stylecheck
      - run: pnpm typecheck
      - run: pnpm build
  list_examples:
    name: List examples
    runs-on: ubuntu-latest
    outputs:
      example_names: ${{ steps.list_examples.outputs.example_names }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "example_names=`find examples/ -mindepth 1 -maxdepth 1 -type d -not -name "bash-client" | jq -R -s -c 'split("\n")[:-1]'`" >> $GITHUB_OUTPUT
        id: list_examples
  check_and_build_examples:
    name: Check and build ${{ matrix.example_folder }}
    needs: [list_examples, build_and_test, check_and_build_react_hooks]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example_folder: ${{ fromJson(needs.list_examples.outputs.example_names) }}
    defaults:
      run:
        working-directory: ${{ matrix.example_folder }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
        name: pnpm build the typescript client
        working-directory: packages/typescript-client
      - run: pnpm build
        name: pnpm build the react hooks
        working-directory: packages/react-hooks
      - run: pnpm typecheck
      - run: pnpm build
