version: "3.1"
name: "electric_dev"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "54321:5432"
    volumes:
      - ./postgres.conf:/etc/postgresql.conf:ro
      - ./init.sql:/docker-entrypoint-initdb.d/00_shared_init.sql:ro
    tmpfs:
      - /var/lib/postgresql/data
      - /tmp
    entrypoint:
      - docker-entrypoint.sh
      - -c
      - config_file=/etc/postgresql.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"


  nginx:
    image: nginx:latest
    ports:
      - "3002:3002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../../caching/nginx_cache:/var/cache/nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
